service: projects

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:eu-west-2:*:*"
  apiKeys:
    - devKey

functions:
  projects:
    handler: projectHandler.projects
    name: ${self:provider.stage}-projectsHandler
    description: Handles API calls related to projects collection
    events:
      - http:
          path: projects
          method: post
          private: true
      - http:
          path: projects
          method: get
          private: true
  project:
    handler: projectHandler.project
    name: ${self:provider.stage}-projectHandler
    description: Handles API calls related to a project
    events:
      - http:
          path: projects/{uuid}
          method: delete
          private: true
      - http:
          path: projects/{uuid}
          method: get
          private: true
      - http:
          path: projects/{uuid}
          method: put
          private: true
  projectDevelopers:
    handler: projectHandler.projectDevelopers
    name: ${self:provider.stage}-projectDevelopersHandler
    descrition: Handles API calls related to developers on a project
    events:
      - http:
          path: projects/{uuid}/developers
          method: post
          private: true
      - http:
          path: projects/{uuid}/developers
          method: delete
          private: true
  user:
    handler: userHandler.users
    name: ${self:provider.stage}-userHandler
    description: Handles API calls related to users
    events:
      - http:
          path: users
          method: post
          private: true
      - http:
          path: users/{sub}
          method: get
          private: true
      - http:
          path: users
          method: get
          private: true
      - http:
          path: users/{sub}
          method: put
          private: true

resources:
  Resources:
    projectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: projects
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: sub
            AttributeType: S
        KeySchema:
          - AttributeName: sub
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

package:
  exclude:
    - node_modules/**
